### ISSUE TITLE
Found version 1.0.0 in nuget.org package source that is not current with documentation

### ISSUE THREAD

**Issue by wbsnipes** [serilog-contrib/SerilogSinksInMemory#35]
Hello, I am happy to find this library fit for my testing requirements, however, I first installed a version 1.0.0 from nuget.org via Visual Studio.  It has a date published of May 23rd, 2024 (today) and the correct contact information for this library.  A corresponding Serilog.Sinks.InMemory.Assertions 1.0.0 version is also available.  Neither version has the supported API in documentation and tests matching the release 0.11.0 version on GitHub.  Not sure what gives but could be someone spoofing the library! See linked screenshot.

![Serilog Sinks InMemory Nuget Version info](https://github.com/serilog-contrib/SerilogSinksInMemory/assets/3738493/344b999a-7dc0-4108-acee-2b1898e245f8)

**Comment by sandermvanvliet** [comment]
Ho hum. Let me investigate this 🤔

**Comment by Tanzy** [comment]
Did you discover what this issue is? Just updated to v1 and encountered this

**Comment by sandermvanvliet** [comment]
It’s strange you see that because 1.0.0 isn’t listed anymore on nuget.org at all. 

Are you by any chance using a package cache like CloudSmith or Artifactory?

**Comment by Tanzy** [comment]
sorry for late reply been away. Yep, looks like our ADO was caching it thanks, did not think to check that

**Comment by sandermvanvliet** [comment]
No worries 👍 glad you were able to find it
